#104 Use-schema_translate_map-in-get_lastrowid
exasol/sqlalchemy-exasol pull request #122
Opened 2022-03-30 12:19 UTC by Nicoretti

For futher details see https://github.com/exasol/sqlalchemy-exasol/issues/104

2022-03-30 14:32 UTC, tkilias requested changes

2022-03-30 14:32 UTC, tkilias commented on sqlalchemy_exasol/base.py
> +            schema_dispatcher = dict(translate_map.map_) if translate_map else {}
I though the map_ is already a dict

2022-03-30 14:32 UTC, tkilias commented on sqlalchemy_exasol/base.py
> +        def _schema(sql_compiler, dialect):
```suggestion
        def _get_schema(sql_compiler, dialect):
```

2022-03-30 14:32 UTC, tkilias commented on sqlalchemy_exasol/base.py
> +            "AND column_schema = ?" if schema else ""
a bit to much magic for my taste, please split into to commands, or put parts into variables

2022-03-30 14:32 UTC, Nicoretti commented on sqlalchemy_exasol/base.py
> +            schema_dispatcher = dict(translate_map.map_) if translate_map else {}
good point

2022-03-31 09:21 UTC, tkilias approved these changes

2022-03-31 09:40 UTC, merged