documentation/#117 evaluate skipped integration tests
exasol/sqlalchemy-exasol pull request #134
Opened 2022-05-06 08:22 UTC by Nicoretti

- Add nox task to run all tests and report the results as json
- Add inital version of script for reporting skipped tests

2022-05-24 14:52 UTC, tkilias requested changes

2022-05-24 14:52 UTC, tkilias commented on noxfile.py
> +sys.path.append(f"{SCRIPTS}")
do we need this whey call report via subprocess

2022-05-25 06:00 UTC, Nicoretti commented on noxfile.py
> +sys.path.append(f"{SCRIPTS}")
No it's not needed for the report, but for the link check.

2022-05-25 06:04 UTC, tkilias commented on noxfile.py
> +sys.path.append(f"{SCRIPTS}")
Maybe add comment

2022-05-25 06:18 UTC, tkilias approved these changes

2022-05-25 07:05 UTC, merged