Fix unexpected auto commits
exasol/sqlalchemy-exasol pull request #336
Opened 2023-05-12 10:46 UTC by Nicoretti

closes #335 

## Todo's 
- [x] Add regression test for invalid autocommit behavior (Issue-335)
- [x] Fix invalid auto-commit behavior
- [ ] Cleanup
    - Cleanup regression test code
    - Add config options for odbc settings
    - Create ticket for consolidating fixtures and odbc setup
- [ ] Add regression tests to CI (integration test target)
- [ ] Update change log

2023-05-12 11:51 UTC, redcatbear requested changes
Minor suggestions.

2023-05-12 11:51 UTC, redcatbear commented on sqlalchemy_exasol/base.py
> +        with closing(self.create_cursor()) as cursor:
I knew you would find a way to keep the `with`. :-)

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/conftest.py
Intentionally empty?

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/test_regression_bug335.py
Number in the name is good. Description would be better. Both together perfect.

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/test_regression_bug335.py
> +ODBC_DRIVER = PROJECT_ROOT / "driver" / "libexaodbc-uo2214lv2.so"
Do you want to hard-code this here, or is auto-inferrence possible?

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/test_regression_bug335.py
> +    For further details on this regression see `Issue-335 <https://github.com/exasol/sqlalchemy-exasol/issues/335>`_.
:+1:

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/test_regression_bug335.py
> +        # insert without and explicit id will trigger get_lastrowid
```suggestion
        # insert without an explicit ID will trigger get_lastrowid
```

2023-05-12 11:51 UTC, redcatbear commented on test/integration/regression/test_regression_bug335.py
> +        conn.execute(insert_statement)
I am guessing here is where the implicit commit happened before. Maybe you should add a comment here.

2023-05-12 11:59 UTC, Nicoretti commented on sqlalchemy_exasol/base.py
> +        with closing(self.create_cursor()) as cursor:
Actually, for this one I got a tip from @tkilias ;) (did not had this stdlib function on the radar so far).

2023-05-12 14:05 UTC, tkilias submitted a review, later dismissed

2023-05-12 14:05 UTC, tkilias commented on test/integration/regression/test_regression_bug335.py
> +sys.path.append(f"{SCRIPTS.resolve()}")
ahhh, this is dirty. for what do you need this?

2023-05-12 14:05 UTC, tkilias commented on test/integration/regression/test_regression_bug335.py
> +def test_schema(control_connection):
What does the fixture control_connection mean here, in the implementation it looks like a connection to the test db?

2023-05-12 14:05 UTC, tkilias commented on test/integration/regression/test_regression_bug335.py
> +def test_schema(control_connection):
Do you mean with control, system under test or check or something like that?

2023-05-15 05:44 UTC, Nicoretti commented on test/integration/regression/conftest.py
Yes

2023-05-15 08:00 UTC, Nicoretti commented on test/integration/regression/test_regression_bug335.py
> +def test_schema(control_connection):
This connection is intended to setup/teardown etc.  rather than executing actual queries for the actual test.

2023-05-15 11:18 UTC, redcatbear approved these changes

2023-05-15 13:47 UTC, merged