bug/#342 failing sqla compliance tests for ws dialect
exasol/sqlalchemy-exasol pull request #357
Opened 2023-07-14 06:42 UTC by Nicoretti

Fixes #342

- Reenable test for issue #342
- Convert Decimal type to float if decimal isn't enforced
- Mark unsupported feature as xfail
- Update changelog

2023-07-14 07:45 UTC, kaklakariada approved these changes

2023-07-14 09:24 UTC, tkilias requested changes

2023-07-14 09:24 UTC, tkilias commented on test/integration/sqlalchemy/test_suite.py
> +        reason="This currently isn't supported by the websocket protocol L3-1064.",
Do we need a tracking ticket in Github?

2023-07-17 06:13 UTC, Nicoretti commented on test/integration/sqlalchemy/test_suite.py
> +        reason="This currently isn't supported by the websocket protocol L3-1064.",
Discussed this with @redcatbear, ID is ok but no links.

2023-07-17 07:30 UTC, tkilias approved these changes

2023-07-17 09:03 UTC, merged